// donaction-saas/src/components/sponsorshipForm/components/formBody/steps/step5/step5.svelte
<script lang="ts">
  import {
    FORM_CONFIG,
    isLoading,
    SUBSCRIPTION,
    triggerValidation,
  } from '../../../../logic/useSponsorshipForm.svelte';
  import { onMount } from 'svelte';
  import Share from '../../../../../../utils/share/Share.svelte';
  import { sendGaEvent } from '../../../../../../utils/sendGaEvent';

  let { index }: { index: number } = $props();

  onMount(() => {
    sendGaEvent({
      step: 5,
      category: 'donation',
      label: `Donation payed, don uuid: ${FORM_CONFIG.donUuid}`,
    });
    // eventBus.events.clear();
    // Object.keys(defVals).forEach((_) => {
    //   DEFAULT_VALUES[_] = defVals[_];
    // });
    FORM_CONFIG.donUuid = null;
    FORM_CONFIG.donatorUuid = null;
    // FORM_CONFIG.clubUuid = null;
    // FORM_CONFIG.projectUuid = null;
    // isBeingFilled.set(false);
    triggerValidation.set(0);
    // index.set(0);
    isLoading.set(false);
    // SUBSCRIPTION.klubr = null;
    // SUBSCRIPTION.project = null;
  });
</script>

<div class="step5 flex w-full flex-col items-center gap-3">
  <div class="flex flex-col items-center gap-1">
    <p>Votre soutien a bien été pris en compte</p>
    <p class="merci">MERCI</p>
  </div>
  <div class="flex flex-col items-center gap-1">
    <img
      width={(SUBSCRIPTION.klubr?.logo?.width / SUBSCRIPTION.klubr?.logo?.height) * 70}
      height={70}
      src={SUBSCRIPTION.klubr?.logo?.url}
      alt="logo club"
    />
    <p>
      Toute l'équipe de <b>{SUBSCRIPTION.klubr?.denomination}</b> vous remercie de votre précieux soutien
    </p>
  </div>

  <a
    style="text-decoration: none; max-width: 80vw;"
    class="primary-btn text-center"
    href={`${import.meta.env.VITE_NEXT_URL}/mes-dons`}>Retrouver mes dons</a
  >

  <div class="flex flex-col items-center gap-1">
    <p>
      Permettez à vos amis de soutenir <b>{SUBSCRIPTION.klubr?.denomination}</b> en partageant ses projets
    </p>
    <Share></Share>
  </div>
</div>

<style lang="scss">
  @use 'index';
</style>

// donaction-frontend/src/layouts/partials/sponsorshipForm/steps/step5.tsx
import React from 'react';
import { Klub } from '@/core/models/club';
import ShareCta from '@/components/Share';
import { KlubProjet } from '@/core/models/klub-project';
import Link from 'next/link';
import ImageHtml from '@/components/media/ImageHtml';

const Step5 = ({ club, projet, email }: { club: Klub; projet?: KlubProjet; email: string }) => {
	const text = projet
		? `Soutenez le projet "${projet.titre}" (${club.denomination})`
		: `Soutenez ${club.denomination}`;
	return (
		<div className='w-full flex flex-col items-center gap-16 text-sm'>
			<div className="flex flex-col items-center gap-2">
				<p className='font-bold'>Votre soutien a bien été pris en compte.</p>
				<p className='text-6xl tracking-widest'>MERCI</p>
			</div>
			<div className="flex flex-col items-center gap-2">
				<ImageHtml
					src={club?.logo?.url}
					alt={club?.logo?.alt}
					width={club?.logo?.width / club?.logo?.height * 70}
					height={70}
					namedtransformation={'logo'}
					className={'h-[70px]'}
				/>
				<p className='text-center'>
					Toute l’équipe de <b>{club.denomination}</b> vous remercie de votre précieux soutien.
				</p>
			</div>
			<Link className={'btn btn-primary'} href={`/mes-dons?email=${email}`}>
				Retrouver mes dons
			</Link>
			<div className="flex flex-col items-center gap-6">
				<p className='md:mt-2 mt-2 text-center'>
					Permettez à vos amis de soutenir <b>{club.denomination}</b> en partageant ses projets
				</p>
				<ShareCta text={text}/>
			</div>
		</div>
	);
};

export default Step5;
