// klubr-frontend/src/layouts/components/LottieAnimation.tsx
'use client';

import React, { useEffect, useRef } from 'react';
import lottie, { AnimationItem } from 'lottie-web';

interface LottieAnimationProps {
	animation: any;
	isControlled?: boolean;
	goToFrame?: number;
}
const LottieAnimation: React.FC<LottieAnimationProps> = (props) => {
	const animationContainer = useRef<HTMLDivElement | null>(null);
	const animationInstance = useRef<AnimationItem>();
	const fromFrame = useRef<number>(props.goToFrame || 0);
	const totalFrameCount = useRef<number>(0);

	useEffect(() => {
		if (animationContainer.current) {
			animationInstance.current = lottie.loadAnimation({
				container: animationContainer.current,
				renderer: 'svg',
				loop: !props?.isControlled,
				autoplay: !props.isControlled,
				animationData: props.animation,
			});
			animationInstance.current?.addEventListener('DOMLoaded', () => {
				totalFrameCount.current = animationInstance.current?.totalFrames || 0;
			});
		}

		return () => {
			animationInstance.current?.destroy();
		};
	}, []);

	useEffect(() => {
		if (animationInstance.current && props.isControlled && typeof props.goToFrame === 'number') {
			console.log(totalFrameCount.current);

			const getCondition = (val: number) => val >= 0 && val <= totalFrameCount.current;

			const goTo = getCondition(props.goToFrame) ? props.goToFrame : fromFrame.current;
			if (fromFrame.current !== goTo) {
				animationInstance.current?.playSegments([fromFrame.current, goTo], true);
			}
			fromFrame.current = goTo;
		}
	}, [props.goToFrame]);

	return <div className='lottieAnimationContainer w-full' ref={animationContainer}></div>;
};

export default LottieAnimation;

// donaction-saas/src/utils/lottie/LottieAnimation.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import lottie, { AnimationItem } from 'lottie-web';

  let {
    segment,
    animation,
    goToFrame,
    isControlled
  }: {
    animation: JSON;
    isControlled: boolean | undefined;
    goToFrame: { value: number; cap: number; override?: boolean } | undefined;
    segment:
      | {
          start_frame: number;
          end_frame: number;
        }
      | undefined;
  } = $props();

  let animationContainer = HTMLDivElement;
  let animationInstance = AnimationItem;
  let totalFrameCount = $state(0);

  onMount(() => {
    if (animationContainer) {
      animationInstance = lottie.loadAnimation({
        container: animationContainer,
        renderer: 'svg',
        loop: !isControlled,
        autoplay: !isControlled,
        animationData: animation
      });

      animationInstance?.addEventListener('DOMLoaded', () => {
        totalFrameCount = animationInstance?.totalFrames || 0;
      });

      if (animationInstance && isControlled && goToFrame && segment) {
        // animationInstance?.addEventListener('enterFrame', (event) => {
        //   const currentFrame = event.currentTime;
        //   console.table({
        //     CurrentFrame: currentFrame,
        //     GoToFrameValue: goToFrame?.value,
        //     GoToFrameCap: goToFrame?.cap,
        //     percentGoToFrame:
        //       (segment.end_frame - segment.start_frame) * (goToFrame?.value / goToFrame?.cap),
        //     StartFrame: segment?.start_frame,
        //     EndFrame: segment?.end_frame,
        //     TotalFrameCount: animationInstance?.totalFrames
        //   });
        // });
      }
    }
  });

  let timeout: number = NaN;

  const debounce = () => {
    if (!isNaN(timeout)) {
      clearTimeout(timeout);
    }
    timeout = setTimeout(() => {
      animationInstance?.playSegments([segment?.start_frame, segment?.end_frame], true);

      clearTimeout(timeout);
    }, 300);
  };

  $effect(() => {
    if (totalFrameCount && animationInstance && isControlled && goToFrame && segment) {
      if (goToFrame?.override) {
        debounce();
      } else {
        clearTimeout(timeout);
        animationInstance?.setSegment(segment?.start_frame, segment?.end_frame);
        const frame =
          (segment.end_frame - segment.start_frame) * (goToFrame?.value / goToFrame?.cap);
        animationInstance?.goToAndStop(frame, true);
      }
    }
  });
</script>

<div class="lottieAnimationContainer" bind:this={animationContainer}></div>

<style>
  .lottieAnimationContainer {
    width: 100%;
  }
</style>
